name: Deploy Backend
on:
  push:
    branches:
      - main
      - switch-to-terra

jobs:
  deploy:
    environment: prod
    env:
      GCP_PROJECT: ${{ vars.GCP_PROJECT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT }}

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Set up CA Certificate
        run: |
          printf "%s\n" "${{ secrets.DB_CA_CERT }}" > backend/ca.pem

      - name: Build Backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_EXTRA_CA_CERTS: ca.pem
        working-directory: backend
        run: |
          npm ci
          ./build-for-prod.sh

      - name: Build Docker image for backend and push to Artifact Registry
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          cd backend
          docker build -t europe-west2-docker.pkg.dev/${{ vars.GCP_PROJECT }}/docker/bucket-bot:$GIT_SHA .
          docker push europe-west2-docker.pkg.dev/${{ vars.GCP_PROJECT }}/docker/bucket-bot:$GIT_SHA
